[package]
name = "ZoteroCoverage"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.32", features=["derive"]}
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
regex = "1.11.1"
clap-file = "0.2.0"
yaml-front-matter = "0.1.0"
shellexpand = "3.1.1"
